# Author: Gatlin Lawson
collegeName = input("College Name: ")
adjective1 = input("Adjective: ")
bodyPart = input("Body Part: ")
Object = input("Object: ")
smell = input("Smell: ")
action = input("Action: ")
adjective2 = input("Adjective: ")
print(f"Let's begin shall we?")
print(f"It was the one night everybody dreads, the night before dark week starts")
print(f"- AKA finals week- at {collegeName}.")
print(f"The library was full of {adjective1} students all glued to their books and {bodyPart}")
print(f"deep in energy drink cans and empty coffee cups.")
print(f"One desperate student even had the guts to sneak in a(n) {Object}.")
print(f"As expected, I couldn't find a decent place to sit so I had to sit next")
print(f"to the dude who smelled like {smell}.")
print(f"I began to {action} {adjective2}.")